In [1]:
import pandas as pd

In [2]:
aqi = pd.read_csv('aqi_data.csv')
asthma = pd.read_csv('asthma_cleaned.csv')

In [3]:
asthma.columns.tolist()

['Year',
 'ZIP code',
 'Age Group',
 'Number of Visits',
 'Age-adjusted rate',
 'County Fips code',
 'County',
 'Lat',
 'Lon']

In [4]:
asthma_clean = asthma.drop(['County Fips code', 'Lat','Lon','ZIP code'], axis=1).copy()

In [5]:
asthma_clean

      Year  Age Group  Number of Visits  Age-adjusted rate       County
0     2012          1             221.0         108.600000  Los angeles
1     2012          0             212.0          64.900000  Los angeles
2     2012          1             215.0         113.300000  Los angeles
3     2012          0             223.0          66.000000  Los angeles
4     2012          1             295.0         125.200000  Los angeles
...    ...        ...               ...                ...          ...
4719  2009          0              14.0         168.321586       Lassen
4720  2009          1              16.0          19.176574    El dorado
4721  2009          0              26.0           8.929906    El dorado
4722  2009          1               0.0           0.000000       Nevada
4723  2009          0               0.0           0.000000       Nevada

[4724 rows x 5 columns]

In [6]:
asth = asthma_clean.groupby(['Year','Age Group',pd.Grouper(key='County')]).mean()

In [7]:
asthma_to_merg = asth.reset_index()

In [8]:
aqi = aqi.drop('State',axis=1)

In [9]:
len(asthma_clean['County'].unique().tolist())

58

In [10]:
aqi['Year'] = aqi['Date Local'].str.split('-').str[0]

In [11]:
aqi['Year'] = pd.to_numeric(aqi['Year'])

In [12]:
aqi = aqi.drop('Date Local', axis = 1)

In [13]:
aqi.columns

Index(['County', 'NO2 AQI', 'O3 AQI', 'SO2 AQI', 'CO AQI', 'Year'], dtype='object')

In [14]:
aqi_grouped = aqi.groupby('Year')

In [15]:
aqi_grouper = aqi.groupby(['Year',pd.Grouper(key='County')]).agg(['mean','max','min'])

In [16]:
aqi_grouper

                       NO2 AQI                            O3 AQI              \
                          mean         max        min       mean         max
Year County
2009 Alameda         21.945205   47.000000   4.000000  20.964384   46.000000
     Contra Costa    14.679909   35.000000   3.500000  32.240639  139.500000
     Fresno          26.539726   66.000000   7.000000  52.282192  172.000000
     Humboldt         8.108033   37.000000   0.000000  23.941828   46.000000
     Imperial        31.777778  101.000000   3.000000  38.691667  119.000000
     Los Angeles     35.318174   79.428571   8.500000  33.104247   89.000000
     Orange          23.684211   63.000000   0.000000  35.229917   90.000000
     Riverside       29.719764   77.000000   2.000000  51.259587  161.000000
     Sacramento      20.174886   48.000000   3.000000  38.616438  145.500000
     San Bernardino  34.701370   70.000000  10.500000  51.568493  145.000000
     San Diego       30.468950   71.333333   5.666667  33.693607   76.000000
     Santa Barbara    5.997717   27.000000   0.666667  33.959726   84.250000
     Santa Clara     23.292063   67.000000   4.000000  24.933333   77.000000
     Santa Cruz       4.018315   16.000000   1.000000  28.761905   71.000000
     Solano          18.024862   46.000000   2.000000  26.787293   93.000000
2010 Alameda         21.927198   50.000000   6.000000  22.101648   42.000000
     Contra Costa    13.522831   35.666667   2.000000  29.277626  106.666667
     Fresno          24.157025   76.000000   5.000000  46.261708  179.000000
     Humboldt         7.019231   22.000000   0.000000  25.192308   41.000000
     Imperial        29.618768   79.000000   3.000000  36.932551  116.000000
     Los Angeles     33.705023   79.800000  10.000000  30.785890  108.800000
     Orange          21.302198   68.000000   0.000000  32.623626  101.000000
     Riverside       28.801444   62.000000   6.000000  56.000000  156.000000
     Sacramento      17.893939   60.000000   3.500000  34.779614  135.000000
     San Bernardino  33.591248   64.000000   3.000000  46.718808  142.000000
     San Diego       27.482808   76.000000   4.000000  32.049737   71.000000
     Santa Barbara    5.055936   31.666667   0.666667  34.493379   74.666667
     Santa Clara     22.713699   52.500000   6.000000  27.301370  127.000000
     Solano          17.972067   52.000000   2.000000  27.790503  111.000000
2011 Alameda         24.819178   60.000000   5.000000  21.287671   41.000000
     Contra Costa    15.029680   37.333333   3.000000  28.419635   80.666667
     Fresno          19.901060   46.000000   3.000000  51.763251  151.000000
     Humboldt         6.247649   25.000000   0.000000  25.062696   42.000000
     Imperial        30.652695  106.000000   3.000000  35.691617  101.000000
     Los Angeles     32.608858   90.500000   7.666667  31.111446   73.666667
     Orange          20.896552   57.000000   1.000000  31.252874   51.000000
     Riverside       29.104377   61.000000   3.000000  53.484848  177.000000
     Sacramento      17.357143   44.000000   2.000000  35.091429  135.000000
     San Bernardino  33.268950   73.500000   7.000000  45.939269  156.500000
     San Diego       22.412983   54.000000   4.000000  35.779006   89.000000
     Santa Barbara    5.211781   15.000000   0.666667  33.500639   82.000000
     Santa Clara     20.672603   45.000000   3.500000  27.273973   74.000000
     Solano          18.756164   44.000000   1.000000  27.063014   80.000000
2012 Alameda         23.867606   50.000000   5.000000  22.712676   41.000000
     Contra Costa    14.848816   37.333333   2.333333  31.231785   92.666667
     Fresno          23.278146   62.000000   4.000000  53.738411  201.000000
     Humboldt         3.510018   13.500000   0.000000  26.036885   41.000000
     Imperial        31.414110   90.000000   2.000000  40.616564  150.000000
     Los Angeles     31.567228   77.500000   5.000000  34.707711   84.000000
     Orange          18.780120   53.000000   2.000000  33.671687  101.000000
     Riverside       27.035587   58.000000   6.000000  51.601423  166.000000
     Sacramento      16.697987   48.000000   3.000000  41.895973  151.000000
     San Bernardino  31.111111   57.500000   8.500000  55.366576  144.000000
     San Diego       20.374302   56.000000   5.000000  37.444134   97.000000
     Santa Barbara    4.623770   18.000000   1.000000  34.798907   62.000000
     Santa Clara     19.510929   53.500000   4.500000  27.972678   61.000000
     Solano          17.363388   49.000000   1.000000  27.939891   58.000000

                                 SO2 AQI                          CO AQI  \
                           min      mean        max       min       mean
Year County
2009 Alameda          2.000000  3.443836  23.000000  0.000000   5.671233
     Contra Costa     7.500000  2.885388  11.500000  0.000000   3.919178
     Fresno           5.000000  3.424658  19.000000  0.000000   6.550685
     Humboldt         7.000000  0.686981  37.000000  0.000000   4.445983
     Imperial         3.000000  2.891667  19.000000  0.000000  15.680556
     Los Angeles      4.750000  3.376843  10.000000  0.000000   8.541142
     Orange           5.000000  2.772853  13.000000  0.000000   5.210526
     Riverside        2.000000  3.064897  16.000000  1.000000   6.776119
     Sacramento       4.500000  1.277626   4.000000  0.000000   6.667123
     San Bernardino  11.000000  2.131507  22.000000  0.000000   5.597260
     San Diego       12.666667  5.804110  17.000000  0.333333   9.652055
     Santa Barbara   18.666667  1.754932   5.666667  0.000000   2.014018
     Santa Clara      2.000000  0.774603   9.000000  0.000000   5.888889
     Santa Cruz      13.000000  2.362637   7.000000  0.000000   4.227106
     Solano           4.000000  2.461326  14.000000  0.000000   6.276243
2010 Alameda          1.000000  2.471154  13.000000  0.000000   5.101648
     Contra Costa     3.500000  2.646119  11.333333  0.000000   4.248858
     Fresno           3.000000  1.900826  21.000000  0.000000   5.426997
     Humboldt         4.000000  1.387363   4.000000  0.000000   3.381868
     Imperial         3.000000  2.390029  13.000000  0.000000  13.744868
     Los Angeles      5.000000  2.970046  25.333333  0.000000   7.243790
     Orange           3.000000  1.417582  13.000000  0.000000   4.527473
     Riverside        8.000000  2.288809  21.000000  0.000000   7.299639
     Sacramento       3.000000  0.575758   3.500000  0.000000   5.019284
     San Bernardino  13.000000  2.396648  35.500000  0.000000   5.326331
     San Diego        8.000000  1.281598  12.333333  0.000000   8.338065
     Santa Barbara   18.500000  1.827397   4.333333  0.666667   1.507078
     Santa Clara      0.000000  0.842466   6.500000  0.000000   5.384932
     Solano           3.000000  1.675978  16.000000  0.000000   5.737430
2011 Alameda          1.000000  3.063014  27.000000  0.000000   6.427397
     Contra Costa     4.333333  2.949315   9.000000  0.333333   4.605023
     Fresno           3.000000  1.978799  23.000000  0.000000   4.189046
     Humboldt         8.000000  0.310345   3.000000  0.000000   4.625392
     Imperial         8.000000  2.215569  13.000000  0.000000  14.754491
     Los Angeles      6.250000  2.438615  19.333333  0.000000   7.255114
     Orange           8.000000  0.925287  10.000000  0.000000   4.672414
     Riverside        1.000000  0.784512  52.500000  0.000000   6.606902
     Sacramento       3.000000  0.420000   6.000000  0.000000   5.125714
     San Bernardino  12.500000  2.155708  11.500000  0.000000   5.519178
     San Diego        5.000000  0.609116   9.500000  0.000000   6.270718
     Santa Barbara   20.000000  2.213242   9.666667  0.333333   2.288584
     Santa Clara      4.000000  1.802740  25.500000  0.000000   5.641096
     Solano           3.000000  1.358904  10.000000  0.000000   7.180822
2012 Alameda          3.000000  2.966197  91.000000  0.000000   7.343662
     Contra Costa    13.000000  1.897541  12.666667  0.000000   4.322404
     Fresno           3.000000  1.248344  11.000000  0.000000   6.543046
     Humboldt        10.500000  0.037796   1.500000  0.000000   3.831967
     Imperial         5.000000  2.441718  21.000000  0.000000  10.024540
     Los Angeles      3.500000  1.999696  26.000000  0.000000   7.741462
     Orange          11.000000  0.268072   9.000000  0.000000   3.433735
     Riverside        3.000000  0.277580   3.000000  0.000000   6.330961
     Sacramento       9.000000  0.365772   4.000000  0.000000   4.785235
     San Bernardino  10.000000  1.508197   6.000000  0.000000   4.422131
     San Diego        2.000000  0.008380   1.000000  0.000000   5.212291
     Santa Barbara   20.000000  2.895719  33.000000  0.666667   2.178142
     Santa Clara      6.000000  1.633880  20.500000  0.000000   5.472678
     Solano           8.000000  1.046448  20.000000  0.000000   6.448087


                           max       min
Year County
2009 Alameda         23.000000  1.000000
     Contra Costa     9.333333  1.500000
     Fresno          24.000000  1.000000
     Humboldt        15.000000  1.000000
     Imperial        81.000000  5.000000
     Los Angeles     22.250000  1.750000
     Orange          25.000000  0.000000
     Riverside       22.000000  0.000000
     Sacramento      25.500000  2.000000
     San Bernardino  13.500000  1.000000
     San Diego       27.000000  2.666667
     Santa Barbara    4.250000  0.333333
     Santa Clara     24.000000  1.000000
     Santa Cruz      58.000000  1.000000
     Solano          25.000000  1.000000
2010 Alameda         17.000000  1.000000
     Contra Costa     9.333333  2.000000
     Fresno          23.000000  0.000000
     Humboldt        10.000000  0.000000
     Imperial        51.000000  6.000000
     Los Angeles     25.600000  1.750000
     Orange          24.000000  0.000000
     Riverside       22.000000  2.000000
     Sacramento      18.000000  1.000000
     San Bernardino  26.000000  0.000000
     San Diego       25.000000  1.000000
     Santa Barbara    4.333333  0.333333
     Santa Clara     25.000000  1.000000
     Solano          22.000000  0.000000
2011 Alameda         31.000000  0.000000
     Contra Costa    10.000000  2.000000
     Fresno          21.000000  1.500000
     Humboldt        11.000000  1.000000
     Imperial        67.000000  0.000000
     Los Angeles     24.600000  0.666667
     Orange          25.000000  0.000000
     Riverside       15.500000  1.500000
     Sacramento      26.000000  1.000000
     San Bernardino  16.000000  0.500000
     San Diego       18.500000  2.000000
     Santa Barbara    4.666667  0.333333
     Santa Clara     16.500000  1.000000
     Solano          27.000000  2.000000
2012 Alameda         27.000000  2.000000
     Contra Costa     9.333333  2.000000
     Fresno          24.000000  1.000000
     Humboldt         7.000000  1.000000
     Imperial        55.000000  1.000000
     Los Angeles     28.500000  2.000000
     Orange          17.000000  0.000000
     Riverside       18.000000  1.000000
     Sacramento      23.000000  1.000000
     San Bernardino  20.000000  0.500000
     San Diego       22.000000  2.000000
     Santa Barbara    4.666667  0.666667
     Santa Clara     15.000000  2.000000
     Solano          25.000000  2.000000

In [17]:
aqi_cleaned = aqi_grouper.reset_index()

In [18]:
aqi_cleaned

    Year          County    NO2 AQI                            O3 AQI  \
                               mean         max        min       mean
0   2009         Alameda  21.945205   47.000000   4.000000  20.964384
1   2009    Contra Costa  14.679909   35.000000   3.500000  32.240639
2   2009          Fresno  26.539726   66.000000   7.000000  52.282192
3   2009        Humboldt   8.108033   37.000000   0.000000  23.941828
4   2009        Imperial  31.777778  101.000000   3.000000  38.691667
5   2009     Los Angeles  35.318174   79.428571   8.500000  33.104247
6   2009          Orange  23.684211   63.000000   0.000000  35.229917
7   2009       Riverside  29.719764   77.000000   2.000000  51.259587
8   2009      Sacramento  20.174886   48.000000   3.000000  38.616438
9   2009  San Bernardino  34.701370   70.000000  10.500000  51.568493
10  2009       San Diego  30.468950   71.333333   5.666667  33.693607
11  2009   Santa Barbara   5.997717   27.000000   0.666667  33.959726
12  2009     Santa Clara  23.292063   67.000000   4.000000  24.933333
13  2009      Santa Cruz   4.018315   16.000000   1.000000  28.761905
14  2009          Solano  18.024862   46.000000   2.000000  26.787293
15  2010         Alameda  21.927198   50.000000   6.000000  22.101648
16  2010    Contra Costa  13.522831   35.666667   2.000000  29.277626
17  2010          Fresno  24.157025   76.000000   5.000000  46.261708
18  2010        Humboldt   7.019231   22.000000   0.000000  25.192308
19  2010        Imperial  29.618768   79.000000   3.000000  36.932551
20  2010     Los Angeles  33.705023   79.800000  10.000000  30.785890
21  2010          Orange  21.302198   68.000000   0.000000  32.623626
22  2010       Riverside  28.801444   62.000000   6.000000  56.000000
23  2010      Sacramento  17.893939   60.000000   3.500000  34.779614
24  2010  San Bernardino  33.591248   64.000000   3.000000  46.718808
25  2010       San Diego  27.482808   76.000000   4.000000  32.049737
26  2010   Santa Barbara   5.055936   31.666667   0.666667  34.493379
27  2010     Santa Clara  22.713699   52.500000   6.000000  27.301370
28  2010          Solano  17.972067   52.000000   2.000000  27.790503
29  2011         Alameda  24.819178   60.000000   5.000000  21.287671
30  2011    Contra Costa  15.029680   37.333333   3.000000  28.419635
31  2011          Fresno  19.901060   46.000000   3.000000  51.763251
32  2011        Humboldt   6.247649   25.000000   0.000000  25.062696
33  2011        Imperial  30.652695  106.000000   3.000000  35.691617
34  2011     Los Angeles  32.608858   90.500000   7.666667  31.111446
35  2011          Orange  20.896552   57.000000   1.000000  31.252874
36  2011       Riverside  29.104377   61.000000   3.000000  53.484848
37  2011      Sacramento  17.357143   44.000000   2.000000  35.091429
38  2011  San Bernardino  33.268950   73.500000   7.000000  45.939269
39  2011       San Diego  22.412983   54.000000   4.000000  35.779006
40  2011   Santa Barbara   5.211781   15.000000   0.666667  33.500639
41  2011     Santa Clara  20.672603   45.000000   3.500000  27.273973
42  2011          Solano  18.756164   44.000000   1.000000  27.063014
43  2012         Alameda  23.867606   50.000000   5.000000  22.712676
44  2012    Contra Costa  14.848816   37.333333   2.333333  31.231785
45  2012          Fresno  23.278146   62.000000   4.000000  53.738411
46  2012        Humboldt   3.510018   13.500000   0.000000  26.036885
47  2012        Imperial  31.414110   90.000000   2.000000  40.616564
48  2012     Los Angeles  31.567228   77.500000   5.000000  34.707711
49  2012          Orange  18.780120   53.000000   2.000000  33.671687
50  2012       Riverside  27.035587   58.000000   6.000000  51.601423
51  2012      Sacramento  16.697987   48.000000   3.000000  41.895973
52  2012  San Bernardino  31.111111   57.500000   8.500000  55.366576
53  2012       San Diego  20.374302   56.000000   5.000000  37.444134
54  2012   Santa Barbara   4.623770   18.000000   1.000000  34.798907
55  2012     Santa Clara  19.510929   53.500000   4.500000  27.972678
56  2012          Solano  17.363388   49.000000   1.000000  27.939891

                            SO2 AQI                          CO AQI  \
           max        min      mean        max       min       mean
0    46.000000   2.000000  3.443836  23.000000  0.000000   5.671233
1   139.500000   7.500000  2.885388  11.500000  0.000000   3.919178
2   172.000000   5.000000  3.424658  19.000000  0.000000   6.550685
3    46.000000   7.000000  0.686981  37.000000  0.000000   4.445983
4   119.000000   3.000000  2.891667  19.000000  0.000000  15.680556
5    89.000000   4.750000  3.376843  10.000000  0.000000   8.541142
6    90.000000   5.000000  2.772853  13.000000  0.000000   5.210526
7   161.000000   2.000000  3.064897  16.000000  1.000000   6.776119
8   145.500000   4.500000  1.277626   4.000000  0.000000   6.667123
9   145.000000  11.000000  2.131507  22.000000  0.000000   5.597260
10   76.000000  12.666667  5.804110  17.000000  0.333333   9.652055
11   84.250000  18.666667  1.754932   5.666667  0.000000   2.014018
12   77.000000   2.000000  0.774603   9.000000  0.000000   5.888889
13   71.000000  13.000000  2.362637   7.000000  0.000000   4.227106
14   93.000000   4.000000  2.461326  14.000000  0.000000   6.276243
15   42.000000   1.000000  2.471154  13.000000  0.000000   5.101648
16  106.666667   3.500000  2.646119  11.333333  0.000000   4.248858
17  179.000000   3.000000  1.900826  21.000000  0.000000   5.426997
18   41.000000   4.000000  1.387363   4.000000  0.000000   3.381868
19  116.000000   3.000000  2.390029  13.000000  0.000000  13.744868
20  108.800000   5.000000  2.970046  25.333333  0.000000   7.243790
21  101.000000   3.000000  1.417582  13.000000  0.000000   4.527473
22  156.000000   8.000000  2.288809  21.000000  0.000000   7.299639
23  135.000000   3.000000  0.575758   3.500000  0.000000   5.019284
24  142.000000  13.000000  2.396648  35.500000  0.000000   5.326331
25   71.000000   8.000000  1.281598  12.333333  0.000000   8.338065
26   74.666667  18.500000  1.827397   4.333333  0.666667   1.507078
27  127.000000   0.000000  0.842466   6.500000  0.000000   5.384932
28  111.000000   3.000000  1.675978  16.000000  0.000000   5.737430
29   41.000000   1.000000  3.063014  27.000000  0.000000   6.427397
30   80.666667   4.333333  2.949315   9.000000  0.333333   4.605023
31  151.000000   3.000000  1.978799  23.000000  0.000000   4.189046
32   42.000000   8.000000  0.310345   3.000000  0.000000   4.625392
33  101.000000   8.000000  2.215569  13.000000  0.000000  14.754491
34   73.666667   6.250000  2.438615  19.333333  0.000000   7.255114
35   51.000000   8.000000  0.925287  10.000000  0.000000   4.672414
36  177.000000   1.000000  0.784512  52.500000  0.000000   6.606902
37  135.000000   3.000000  0.420000   6.000000  0.000000   5.125714
38  156.500000  12.500000  2.155708  11.500000  0.000000   5.519178
39   89.000000   5.000000  0.609116   9.500000  0.000000   6.270718
40   82.000000  20.000000  2.213242   9.666667  0.333333   2.288584
41   74.000000   4.000000  1.802740  25.500000  0.000000   5.641096
42   80.000000   3.000000  1.358904  10.000000  0.000000   7.180822
43   41.000000   3.000000  2.966197  91.000000  0.000000   7.343662
44   92.666667  13.000000  1.897541  12.666667  0.000000   4.322404
45  201.000000   3.000000  1.248344  11.000000  0.000000   6.543046
46   41.000000  10.500000  0.037796   1.500000  0.000000   3.831967
47  150.000000   5.000000  2.441718  21.000000  0.000000  10.024540
48   84.000000   3.500000  1.999696  26.000000  0.000000   7.741462
49  101.000000  11.000000  0.268072   9.000000  0.000000   3.433735
50  166.000000   3.000000  0.277580   3.000000  0.000000   6.330961
51  151.000000   9.000000  0.365772   4.000000  0.000000   4.785235
52  144.000000  10.000000  1.508197   6.000000  0.000000   4.422131
53   97.000000   2.000000  0.008380   1.000000  0.000000   5.212291
54   62.000000  20.000000  2.895719  33.000000  0.666667   2.178142
55   61.000000   6.000000  1.633880  20.500000  0.000000   5.472678
56   58.000000   8.000000  1.046448  20.000000  0.000000   6.448087


          max       min
0   23.000000  1.000000
1    9.333333  1.500000
2   24.000000  1.000000
3   15.000000  1.000000
4   81.000000  5.000000
5   22.250000  1.750000
6   25.000000  0.000000
7   22.000000  0.000000
8   25.500000  2.000000
9   13.500000  1.000000
10  27.000000  2.666667
11   4.250000  0.333333
12  24.000000  1.000000
13  58.000000  1.000000
14  25.000000  1.000000
15  17.000000  1.000000
16   9.333333  2.000000
17  23.000000  0.000000
18  10.000000  0.000000
19  51.000000  6.000000
20  25.600000  1.750000
21  24.000000  0.000000
22  22.000000  2.000000
23  18.000000  1.000000
24  26.000000  0.000000
25  25.000000  1.000000
26   4.333333  0.333333
27  25.000000  1.000000
28  22.000000  0.000000
29  31.000000  0.000000
30  10.000000  2.000000
31  21.000000  1.500000
32  11.000000  1.000000
33  67.000000  0.000000
34  24.600000  0.666667
35  25.000000  0.000000
36  15.500000  1.500000
37  26.000000  1.000000
38  16.000000  0.500000
39  18.500000  2.000000
40   4.666667  0.333333
41  16.500000  1.000000
42  27.000000  2.000000
43  27.000000  2.000000
44   9.333333  2.000000
45  24.000000  1.000000
46   7.000000  1.000000
47  55.000000  1.000000
48  28.500000  2.000000
49  17.000000  0.000000
50  18.000000  1.000000
51  23.000000  1.000000
52  20.000000  0.500000
53  22.000000  2.000000
54   4.666667  0.666667
55  15.000000  2.000000
56  25.000000  2.000000

In [19]:
aqi_cleaned['County'] = aqi_cleaned['County'].str.lower().str.capitalize()

In [20]:
asthma_to_merg['Year'].dtype

dtype('int64')

In [21]:
merged = asthma_to_merg.merge(aqi_cleaned, how='inner', on=['County','Year'])

C:\Users\Rodrigo\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:648: UserWarning: merging between different levels can give an unintended result (1 levels on the left,2 on the right)
  warnings.warn(msg, UserWarning)
C:\Users\Rodrigo\Anaconda3\lib\site-packages\pandas\core\generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

In [22]:
print(f'rows: {len(merged)}, columns: {len(merged.columns.tolist())}')

rows: 54, columns: 17

In [23]:
merged

,Year,Age Group,County,Number of Visits,Age-adjusted rate,"(NO2 AQI, mean)","(NO2 AQI, max)","(NO2 AQI, min)","(O3 AQI, mean)","(O3 AQI, max)","(O3 AQI, min)","(SO2 AQI, mean)","(SO2 AQI, max)","(SO2 AQI, min)","(CO AQI, mean)","(CO AQI, max)","(CO AQI, min)"
0,2009,0,Alameda,146.217391,57.952969,21.945205,47.000000,4.000000,20.964384,46.00,2.000000,3.443836,23.000000,0.000000,5.671233,23.000000,1.000000
1,2009,1,Alameda,88.347826,102.251601,21.945205,47.000000,4.000000,20.964384,46.00,2.000000,3.443836,23.000000,0.000000,5.671233,23.000000,1.000000
2,2009,0,Contra costa,129.277778,56.074682,14.679909,35.000000,3.500000,32.240639,139.50,7.500000,2.885388,11.500000,0.000000,3.919178,9.333333,1.500000
3,2009,1,Contra costa,69.194444,70.746074,14.679909,35.000000,3.500000,32.240639,139.50,7.500000,2.885388,11.500000,0.000000,3.919178,9.333333,1.500000
4,2009,0,Fresno,79.390244,47.221375,26.539726,66.000000,7.000000,52.282192,172.00,5.000000,3.424658,19.000000,0.000000,6.550685,24.000000,1.000000
5,2009,1,Fresno,84.463415,107.622145,26.539726,66.000000,7.000000,52.282192,172.00,5.000000,3.424658,19.000000,0.000000,6.550685,24.000000,1.000000
6,2009,0,Humboldt,55.444444,77.700310,8.108033,37.000000,0.000000,23.941828,46.00,7.000000,0.686981,37.000000,0.000000,4.445983,15.000000,1.000000
7,2009,1,Humboldt,18.777778,48.700272,8.108033,37.000000,0.000000,23.941828,46.00,7.000000,0.686981,37.000000,0.000000,4.445983,15.000000,1.000000
8,2009,0,Imperial,78.777778,99.638590,31.777778,101.000000,3.000000,38.691667,119.00,3.000000,2.891667,19.000000,0.000000,15.680556,81.000000,5.000000
9,2009,1,Imperial,91.222222,156.885517,31.777778,101.000000,3.000000,38.691667,119.00,3.000000,2.891667,19.000000,0.000000,15.680556,81.000000,5.000000
10,2009,0,Los angeles,110.700758,39.232222,35.318174,79.428571,8.500000,33.104247,89.00,4.750000,3.376843,10.000000,0.000000,8.541142,22.250000,1.750000
11,2009,1,Los angeles,80.871212,64.778147,35.318174,79.428571,8.500000,33.104247,89.00,4.750000,3.376843,10.000000,0.000000,8.541142,22.250000,1.750000
12,2009,0,Orange,69.679487,23.753271,23.684211,63.000000,0.000000,35.229917,90.00,5.000000,2.772853,13.000000,0.000000,5.210526,25.000000,0.000000
13,2009,1,Orange,53.000000,46.026959,23.684211,63.000000,0.000000,35.229917,90.00,5.000000,2.772853,13.000000,0.000000,5.210526,25.000000,0.000000
14,2009,0,Riverside,86.596774,38.526469,29.719764,77.000000,2.000000,51.259587,161.00,2.000000,3.064897,16.000000,1.000000,6.776119,22.000000,0.000000
15,2009,1,Riverside,65.419355,63.233751,29.719764,77.000000,2.000000,51.259587,161.00,2.000000,3.064897,16.000000,1.000000,6.776119,22.000000,0.000000
16,2009,0,Sacramento,135.795455,60.351119,20.174886,48.000000,3.000000,38.616438,145.50,4.500000,1.277626,4.000000,0.000000,6.667123,25.500000,2.000000
17,2009,1,Sacramento,63.500000,65.104315,20.174886,48.000000,3.000000,38.616438,145.50,4.500000,1.277626,4.000000,0.000000,6.667123,25.500000,2.000000
18,2009,0,San bernardino,12.000000,79.580788,34.701370,70.000000,10.500000,51.568493,145.00,11.000000,2.131507,22.000000,0.000000,5.597260,13.500000,1.000000
19,2009,1,San bernardino,0.000000,0.000000,34.701370,70.000000,10.500000,51.568493,145.00,11.000000,2.131507,22.000000,0.000000,5.597260,13.500000,1.000000
20,2009,0,San diego,76.825000,24.814073,30.468950,71.333333,5.666667,33.693607,76.00,12.666667,5.804110,17.000000,0.333333,9.652055,27.000000,2.666667
21,2009,1,San diego,63.825000,56.694446,30.468950,71.333333,5.666667,33.693607,76.00,12.666667,5.804110,17.000000,0.333333,9.652055,27.000000,2.666667
22,2009,0,Santa barbara,43.500000,21.014782,5.997717,27.000000,0.666667,33.959726,84.25,18.666667,1.754932,5.666667,0.000000,2.014018,4.250000,0.333333
23,2009,1,Santa barbara,36.812500,49.662206,5.997717,27.000000,0.666667,33.959726,84.25,18.666667,1.754932,5.666667,0.000000,2.014018,4.250000,0.333333
24,2009,0,Santa clara,71.134615,29.701357,23.292063,67.000000,4.000000,24.933333,77.00,2.000000,0.774603,9.000000,0.000000,5.888889,24.000000,1.000000
25,2009,1,Santa clara,36.365385,33.546001,23.292063,67.000000,4.000000,24.933333,77.00,2.000000,0.774603,9.000000,0.000000,5.888889,24.000000,1.000000
26,2009,0,Santa cruz,37.461538,19.756451,4.018315,16.000000,1.000000,28.761905,71.00,13.000000,2.362637,7.000000,0.000000,4.227106,58.000000,1.000000
27,2009,1,Santa cruz,24.692308,23.030913,4.018315,16.000000,1.000000,28.761905,71.00,13.000000,2.362637,7.000000,0.000000,4.227106,58.000000,1.000000
28,2009,0,Solano,172.545455,58.035696,18.024862,46.000000,2.000000,26.787293,93.00,4.000000,2.461326,14.000000,0.000000,6.276243,25.000000,1.000000
29,2009,1,Solano,86.909091,78.475280,18.024862,46.000000,2.000000,26.787293,93.00,4.000000,2.461326,14.000000,0.000000,6.276243,25.000000,1.000000
30,2012,0,Alameda,149.826087,57.521739,23.867606,50.000000,5.000000,22.712676,41.00,3.000000,2.966197,91.000000,0.000000,7.343662,27.000000,2.000000
31,2012,1,Alameda,62.913043,74.869565,23.867606,50.000000,5.000000,22.712676,41.00,3.000000,2.966197,91.000000,0.000000,7.343662,27.000000,2.000000
32,2012,0,Fresno,82.300000,45.750000,23.278146,62.000000,4.000000,53.738411,201.00,3.000000,1.248344,11.000000,0.000000,6.543046,24.000000,1.000000
33,2012,1,Fresno,92.275000,118.265000,23.278146,62.000000,4.000000,53.738411,201.00,3.000000,1.248344,11.000000,0.000000,6.543046,24.000000,1.000000
34,2012,0,Humboldt,58.636364,70.581818,3.510018,13.500000,0.000000,26.036885,41.00,10.500000,0.037796,1.500000,0.000000,3.831967,7.000000,1.000000
35,2012,1,Humboldt,16.000000,51.336364,3.510018,13.500000,0.000000,26.036885,41.00,10.500000,0.037796,1.500000,0.000000,3.831967,7.000000,1.000000
36,2012,0,Imperial,69.222222,76.466667,31.414110,90.000000,2.000000,40.616564,150.00,5.000000,2.441718,21.000000,0.000000,10.024540,55.000000,1.000000
37,2012,1,Imperial,81.888889,170.011111,31.414110,90.000000,2.000000,40.616564,150.00,5.000000,2.441718,21.000000,0.000000,10.024540,55.000000,1.000000
38,2012,0,Los angeles,107.901141,37.360837,31.567228,77.500000,5.000000,34.707711,84.00,3.500000,1.999696,26.000000,0.000000,7.741462,28.500000,2.000000
39,2012,1,Los angeles,77.551331,72.785551,31.567228,77.500000,5.000000,34.707711,84.00,3.500000,1.999696,26.000000,0.000000,7.741462,28.500000,2.000000
40,2012,0,Orange,71.325000,23.657500,18.780120,53.000000,2.000000,33.671687,101.00,11.000000,0.268072,9.000000,0.000000,3.433735,17.000000,0.000000
41,2012,1,Orange,49.950000,46.540000,18.780120,53.000000,2.000000,33.671687,101.00,11.000000,0.268072,9.000000,0.000000,3.433735,17.000000,0.000000
42,2012,0,Riverside,89.125000,37.114062,27.035587,58.000000,6.000000,51.601423,166.00,3.000000,0.277580,3.000000,0.000000,6.330961,18.000000,1.000000
43,2012,1,Riverside,61.421875,60.092188,27.035587,58.000000,6.000000,51.601423,166.00,3.000000,0.277580,3.000000,0.000000,6.330961,18.000000,1.000000
44,2012,0,Sacramento,143.111111,60.537778,16.697987,48.000000,3.000000,41.895973,151.00,9.000000,0.365772,4.000000,0.000000,4.785235,23.000000,1.000000
45,2012,1,Sacramento,61.977778,67.228889,16.697987,48.000000,3.000000,41.895973,151.00,9.000000,0.365772,4.000000,0.000000,4.785235,23.000000,1.000000
46,2012,0,San diego,84.171053,26.102632,20.374302,56.000000,5.000000,37.444134,97.00,2.000000,0.008380,1.000000,0.000000,5.212291,22.000000,2.000000
47,2012,1,San diego,66.552632,64.578947,20.374302,56.000000,5.000000,37.444134,97.00,2.000000,0.008380,1.000000,0.000000,5.212291,22.000000,2.000000
48,2012,0,Santa barbara,45.647059,22.088235,4.623770,18.000000,1.000000,34.798907,62.00,20.000000,2.895719,33.000000,0.666667,2.178142,4.666667,0.666667
49,2012,1,Santa barbara,38.176471,52.605882,4.623770,18.000000,1.000000,34.798907,62.00,20.000000,2.895719,33.000000,0.666667,2.178142,4.666667,0.666667
50,2012,0,Santa clara,70.326923,31.903846,19.510929,53.500000,4.500000,27.972678,61.00,6.000000,1.633880,20.500000,0.000000,5.472678,15.000000,2.000000
51,2012,1,Santa clara,34.807692,34.203846,19.510929,53.500000,4.500000,27.972678,61.00,6.000000,1.633880,20.500000,0.000000,5.472678,15.000000,2.000000
52,2012,0,Solano,201.090909,69.127273,17.363388,49.000000,1.000000,27.939891,58.00,8.000000,1.046448,20.000000,0.000000,6.448087,25.000000,2.000000
53,2012,1,Solano,96.181818,107.563636,17.363388,49.000000,1.000000,27.939891,58.00,8.000000,1.046448,20.000000,0.000000,6.448087,25.000000,2.000000

In [24]:
merged.to_csv('aqi_asthma.csv', index=False)